---
title: "Econometría II"
subtitle: "**Temas Administrativos**"
author: "Mauricio M. Tejada"
institute: "*Departamento de Economía, Universidad Diego Portales*"
format: 
  udp-revealjs:
    footer: "Ingeniería Comercial -- Econometría II"
incremental: false
embed-resources: true
---


## Temas Administrativos

1. *Quien es quien:*

    - Profesor: Mauricio Tejada (email: [mauricio.tejada@mail.udp.cl](mailto:mauricio.tejada@mail.udp.cl)).

    - Ayudante: Por anunciar

2. *Horarios:*

    - Clases: Martes y Jueves 14:30 a 15:50. Sala a ser anunciada.

    - Horas de Oficina: Martes 10:00 a 11:00. Edificio Cubo, piso 5, oficina 502.

    - Ayudantía: Viernes de 16:00 a 17:20. Sala a ser anunciada.

3. *Comunicación:*

    - Email y Canvas.


## Sobre el curso

**Descripción:**

- Este curso es una extensión natural al curso introductorio de econometría. 

- El enfoque girará en torno al uso de distintos tipos de datos y métodos de estimación en el contexto de dichos tipos de datos. 

- Un énfasis especial se pondrá en el uso de estos modelos y estimadores para resolver problemas específicos. 


**Objetivo:**

*Se espera que el alumno conozca los rudimentos de los métodos de estimación bajo distintos tipos de datos y sepa identificar las situaciones en las que éstos deben ser aplicados.*


## Contenidos

- [**Unidad 1:**]{.color-red} Muestras grandes, estimación y propiedades
  
  - Breve repaso MCO, repaso VI, propiedades, métodos de máximo verosimilitud, método de momentos. 
  
- [**Unidad 2:**]{.color-red} Modelos para Datos de Panel

  - Modelo de componentes de error, efectos fijos, efectos aleatorios, inferencia.

- [**Unidad 3:**]{.color-red} Modelos de Series Temporales

  - Efectos cuasales dinámicos, procesos estacionarios, VAR, raíces unitarias, cointegración.

- [**Unidad 4:**]{.color-red} Modelos de Variable Dependiente Limitada

  - Variable dependiente dicotómica, selección muestral (si el tiempo lo permite).


## Bibliografía:

1. Stock, James y Watson, Mark (2012). Introducción a la Econometría. Tercera Edición, Peason. **[SW]**

2. Wooldridge, Jeffrey M. (2015). Introducción a la Econometría. Un Enfoque Moderno. Quinta Edición, CENGAGE Learning. **[W]**

*Nota: Voy a distribuir material adicional principalmente con derivaciones matemáticas no cubiertas en clase.*

## Software

- La aplicación de las técnicas econométricas requiere de un paquete computacional. En este curso [vamos a utilizar R]{.emph}.

- Este paquete es muy popular en estadística y ciencia de los datos. En economía cae aún por detrás de Stata, pero ha tenido un crecimiento importante en los últimos años. 

- **Ventajas:** Es software libre (y por tanto es gratuito) y existe un repositorio enorme de paquetes implementando técnicas econométricas y estadísticas modernas.

## Software

- Referencias útiles:

    - Introduction to Econometrics with R de Christoph Hanck, Martin Arnold, Alexander Gerber y Martin Schmelzer (replica aplicaciones SW): <https://www.econometrics-with-r.org/> 

    - Using R for Introductory Econometrics de Florian Heiss (replica aplicaciones empíricas W): <http://www.urfie.net/>
    
    - Principles of Econometrics with R de Constantin Colonescu (tiene una mezcla de aplicaciones): <https://bookdown.org/ccolonescu/RPoE4/>

## Evaluación 

Formas de evaluación (en base esquema 8445):

* [**Nota de Presentación (70%):**]{.color-red} actividades a llevarse a cabo durante el semestre.
    
    * [**Solemne 1 (30%):**]{.color-red} 21 de abril de 2026.

    * [**Solemne 2 (30%):**]{.color-red} 9 de junio de 2026.

    * [**Controles (Tareas, 20%):**]{.color-red} Dos tareas analíticas a ser entregadas el viernes anterior al inicio de la semana de solemnes.

    * [**Trabajo (Ejercicio Empíricos, 20%):**]{.color-red} 4 a 5 ejercicio empíricos a realizarse durante el semestre (esta
actividad tributa a su e-portafolio).

* [**Examen (30%):**]{.color-red} Semana del 12 al 19 de diciembre.

## Evaluación 

- No hay eximición. La nota mínima de presentación al examen es 3,5. 

- Si un/a estudiante falta a una evaluación, deberá rendir de forma obligatoria el examen para reemplazar la nota pendiente. 

- Solo una evaluación (evaluación 1 o 2) puede ser reemplazada con el examen o evaluación final.

- Solo los/as estudiantes que rindieron ambas evaluaciones podrán justificar su inasistencia a su examen. 

- Dado que los ejercicio empíricos son trabajos realizados con anticipación y entregados vía CANVAS, la no entrega de éstos no es justificable y será evaluada con nota 1.0.

- Conductas deshonestas, plagio y cualquier acción que vicie el proceso de aprendizaje será llevada al *Comité de Ética*.

## Sobre el uso de herramientas de inteligencia artificial

- Para garantizar un aprendizaje óptimo y ético usen de forma responsable las herramientas de inteligencia artificial. 

- El uso de herramientas de inteligencia artificial está permitido en este curso para las siguientes actividades:

  - Discutir y perfeccionar ideas (brainstorming);
  - Refinar preguntas de investigación previamente definidas por el estudiante;
  - Realizar consultas sobre un tema en particular;
  - Elaborar esquemas para organizar ideas; y
  - Revisar gramática y estilo.
  
- Para los usos permitidos citar de acuerdo al siguiente ejemplo: **Chat-GPT-4. (Mes MM y año AAAA de la consulta). “Texto de tu consulta.” Generado con OpenAI. https://chat.openai.com/**.

## Sobre el uso de herramientas de inteligencia artificial

- El uso de herramientas de inteligencia artificial no está permitido en este curso para las siguientes actividades:

  - Suplantar la identidad del estudiante en foros de discusión Canvas o en un chat de Zoom.
  - Completar las partes de un trabajo en grupo que haya sido asignada al estudiante.
  - Escribir oraciones, párrafos o documentos completos para cumplir con las tareas del cursor.
  - Generar códigos de programación (si fuera el caso en este cursor) para cumplir con tareas del curso.  

- El estudiante es responsable de la información que envíe basada en una consulta estas herramientas.

## Sobre el uso de Dispositivos Electrónicos en Clase

Dada la exigencia del curso y la necesidad de mantener un alto nivel de concentración, implementaremos una estricta política de **cero pantallas**. El uso de celulares, laptops, tablets o smartwatches interrumpe el proceso de aprendizaje y distrae tanto al usuario como a sus compañeros, por lo que su uso está totalmente prohibido durante la clase. Les invito a tomar notas a mano (cuaderno y lápiz), una práctica que ha demostrado mejorar la retención y el análisis de la información. Por estas mismas razones pedagógicas, no se autoriza fotografiar la pizarra ni grabar el audio de las sesiones. Solo se realizarán excepciones a esta regla para estudiantes que presenten adaptaciones de aprendizaje o necesidades educativas especiales formalmente documentadas. El uso de laptops será permitido en las ayudantías solo para aquellas sesiones que lo requieran para el trabajo práctico. El cumplimiento de esta política es obligatorio para preservar el ambiente de estudio. En caso de infracción, se le solicitará al estudiante abandonar el aula de clases de manera inmediata.

## Programación tentativa

- Marzo (8 clases):
  - Unidad 1 (6), Unidad 2 (2)

- Abril (7 clases):
  - Unidad 2 (7), [**Solemne 1**]{.color-red}

- Mayo (7 clases):
  - Unidad 3 (7)

- Junio (7 clases):
  - Unidad 3 (4), Unidad 4 (3), [**Solemne 2**]{.color-red}

- Julio (2 clases):
  - Unidad 4 (2)

## Programación tentativa {visibility="hidden"}

|Marzo|Abril|Mayo|Junio|Julio|
|:---:|:---:|:---:|:---:|:---:|
|7 Clases     |7 Clases      |5 Clases      |7 Clases      |1 Clases.      |
|Unidad 1 (3) | Unidad 3 (7) | Unidad 4 (1) | Unidad 4 (1) | Unidad 5 (1)  |
|Unidad 2 (4) |              | Unidad 4 (4) | Unidad 5 (6) |               |
|             |*Solemne 1*   |              | *Solemne 2*  |               | 

## Programación tentativa {visibility="hidden"}

|Agosto|Septiembre|Octubre|Noviembre|Diciembre|
|:---:|:---:|:---:|:---:|:---:|
|7 Clases     |5 Clases      |9 Clases      |6 Clases      |3 Clases.      |
|Unidad 1 (4) | Unidad 2 (1) | Unidad 3 (4) | Unidad 4 (2) | Unidad 5 (3)  |
|Unidad 2 (3) | Unidad 3 (4) | Unidad 4 (5) | Unidad 5 (4) |               |
|             |*Solemne 1*   |              | *Solemne 2*  |               | 

